C:/python/release/python C:/st_sim/usr/dev/sivla/scenarii/ROB__TvfoTriggeredIs___ACCP.PA_AIRP.PA_ALSO.PA_ALUA.PA_AXAF.PA_BNPP.PA_BOUY.PA_CAGR.PA_CAPP.PA_CARR.PA_CNAT.PA_DANO.PA_EAD.PA_EDF.PA_ESSI.PA_FTE.PA_GSZ.PA_LAFP.PA_LVMH.PA_MICP.PA_OREP.PA_PERP.PA_PEUP.PA_PRTP.PA_PUBP.PA_.py
exit
